# ---------------------- #
#      Site Configs      #
# ---------------------- #

author: wǒ_is神仙
name: MrZhang.me
url: http://mrzhang.me
permalink: blog/:title.html
relative_permalinks: false
# paginate: 5
# paginate_path: page-:num
excerpt_separator: '<!-- more -->'


# ---------------------- #
#         Jekyll         #
# ---------------------- #

safe: true
markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock']
timezone: Asia/Shanghai


# ---------------------- #
#      Compile Sass      #
# ---------------------- #

# run `compass help compile` in terminal to find more available options
sass:
  no_line_comments: true
  sass_dir: _sass
  fonts_dir: fonts
  output_style: compressed


# ---------------------- #
#       Deployment       #
# ---------------------- #

deploy:
  repository: git@github.com:jsw0528/MrZhang.me.git
  branch: gh-pages


# ---------------------- #
#    Social Networks     #
# ---------------------- #

weibo:
  username: jsw0528
#   uid:
#   appkey:

github: jsw0528

duoshuo: jsw0528

google_analytics: UA-16622252-5
